FROM php:8.2-apache

# ---- FIX Apache MPM (OBLIGATOIRE) ----
RUN a2dismod mpm_event || true \
 && a2dismod mpm_worker || true \
 && a2enmod mpm_prefork

# Installer extensions PHP
RUN docker-php-ext-install pdo pdo_mysql

# Installer MongoDB extension
RUN pecl install mongodb \
 && docker-php-ext-enable mongodb

# Apache -> dossier public
ENV APACHE_DOCUMENT_ROOT=/var/www/html/public

RUN sed -ri -e 's!/var/www/html!${APACHE_DOCUMENT_ROOT}!g' /etc/apache2/sites-available/*.conf \
 && sed -ri -e 's!/var/www/!${APACHE_DOCUMENT_ROOT}!g' /etc/apache2/apache2.conf /etc/apache2/conf-available/*.conf

# Copier projet
COPY . /var/www/html

RUN chown -R www-data:www-data /var/www/html
